# This will download the official Postgres Docker image from Docker Hub
# Version 18 of the Postgres database will be used, 
# and the operating system that will be used is Trixie (aka Debian 13.0)
FROM postgres:18.0-trixie
