[package]
name = "rust_lab"
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "3"

members = [
  # "01-control-flow/*", 
  "02-enums/*", 
  "03-vectors/*", 
  "04-environment-variables/*"
]
[workspace.dependencies]
