[package]
name = "rust_lab"
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "3"

members = [
  "01-enums/*", 
  "02-vectors/*", 
  "03-environment-variables/*",
  "04-functional-programming/*",
  "05-threads/*", 
  "06-iterators/*"
]

[workspace.dependencies]
