[project]
name = "topic-01-creating-a-class"
version = "0.1.0"
requires-python = "==3.14.0"
dependencies = []

[tool.ruff]
line-length = 80
indent-width = 4

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
